export const DEFAULT_FARMING_TICKET_END_TIME = '9223372036854775807'

export const FARMING_TICKET_SIZE = 584
export const FARMING_TICKET_OFFSET_OF_POOL_PUBLICKEY = 64
export const FARMING_TICKET_OFFSET_OF_USER_PUBLICKEY = 32

export const INSTANT_FARMING_REWARD_PART_NUMERATOR = 1
export const INSTANT_FARMING_REWARD_PART_DENOMINATOR = 3

export const VESTING_FARMING_REWARD_PART_NUMERATOR = 2
export const VESTING_FARMING_REWARD_PART_DENOMINATOR = 3
