name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          
      - name: Install dependencies
        run: |
          # Try to install dependencies, handling the local file dependency issue
          if ! yarn install --ignore-optional; then
            echo "Warning: Some dependencies failed to install. This might be due to local file dependencies."
            echo "Attempting to install without problematic dependencies..."
            # Remove the problematic local dependency temporarily for CI
            npm pkg delete dependencies["@project-serum/common"]
            yarn install --ignore-optional
          fi
        
      - name: Run linter
        run: yarn lint
        
      - name: Run tests
        run: yarn test
        
      - name: Build project
        run: yarn build
        
      - name: Verify package can be packed
        run: npm pack --dry-run